[build]
  command = "yarn build:front && yarn build:functions"
  publish = "packages/front/out"
  functions = "packages/functions/dist"

[[redirects]]
  from = "/you/*"
  to = "/index.html"
  status = 200
