version: 2.1
executors:
  node12:
    docker:
      - image: circleci/node:12
commands:
  setup:
    description: "checkout and yarn install"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  valid:
    executor: node12
    steps:
      - setup
      - run: yarn valid:type
      - run: yarn valid:lint
      - run: yarn valid:test
      - run: yarn valid:jscpd

  doc:
    executor: node12
    steps:
      - setup
      - run: yarn valid:jscpd
      - run: sudo apt-get install -y graphviz
      - run: yarn madge:domain
      - run: yarn madge:useCase
      - run: yarn madge:controller
      - run: yarn madge:presenter
      - run: yarn madge:gateway
      - run: yarn madge:externalInterface
      - run: yarn madge:pages
      - run: yarn madge:all
      - run: yarn netlify deploy --prod -d ./docs --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

workflows:
  app:
    jobs:
      - valid
      - doc
