version: 2.1
executors:
  node12:
    docker:
      - image: circleci/node:12
commands:
  setup:
    description: "checkout and yarn install"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  valid:
    executor: node12
    steps:
      - setup
      - run: yarn valid

  doc:
    executor: node12
    steps:
      - setup
      - run: sudo apt-get install -y graphviz
      - run: yarn workspace @app/front valid:jscpd && mkdir -p docs/jscpd && mv packages/front/docs/jscpd docs
      - run: yarn workspace @app/front run-p "madge:*" && mkdir -p docs/madge && mv packages/front/docs/madge docs
      - run: yarn netlify deploy --prod -d ./docs --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID

workflows:
  app:
    jobs:
      - valid
      - doc
